/*
 * CAMPUSOnline Webservice proxy
 *
 * This is the proxy server for CAMPUSOnline Webservices, enabling a nicely documented and uniform rest access to CAMPUSOnline resources.
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// RoutesCourseCredits struct for RoutesCourseCredits
type RoutesCourseCredits struct {
	HoursPerWeek *string `json:"hours_per_week,omitempty"`
	Text *string `json:"text,omitempty"`
}

// NewRoutesCourseCredits instantiates a new RoutesCourseCredits object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoutesCourseCredits() *RoutesCourseCredits {
	this := RoutesCourseCredits{}
	return &this
}

// NewRoutesCourseCreditsWithDefaults instantiates a new RoutesCourseCredits object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoutesCourseCreditsWithDefaults() *RoutesCourseCredits {
	this := RoutesCourseCredits{}
	return &this
}

// GetHoursPerWeek returns the HoursPerWeek field value if set, zero value otherwise.
func (o *RoutesCourseCredits) GetHoursPerWeek() string {
	if o == nil || o.HoursPerWeek == nil {
		var ret string
		return ret
	}
	return *o.HoursPerWeek
}

// GetHoursPerWeekOk returns a tuple with the HoursPerWeek field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutesCourseCredits) GetHoursPerWeekOk() (*string, bool) {
	if o == nil || o.HoursPerWeek == nil {
		return nil, false
	}
	return o.HoursPerWeek, true
}

// HasHoursPerWeek returns a boolean if a field has been set.
func (o *RoutesCourseCredits) HasHoursPerWeek() bool {
	if o != nil && o.HoursPerWeek != nil {
		return true
	}

	return false
}

// SetHoursPerWeek gets a reference to the given string and assigns it to the HoursPerWeek field.
func (o *RoutesCourseCredits) SetHoursPerWeek(v string) {
	o.HoursPerWeek = &v
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *RoutesCourseCredits) GetText() string {
	if o == nil || o.Text == nil {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutesCourseCredits) GetTextOk() (*string, bool) {
	if o == nil || o.Text == nil {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *RoutesCourseCredits) HasText() bool {
	if o != nil && o.Text != nil {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *RoutesCourseCredits) SetText(v string) {
	o.Text = &v
}

func (o RoutesCourseCredits) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.HoursPerWeek != nil {
		toSerialize["hours_per_week"] = o.HoursPerWeek
	}
	if o.Text != nil {
		toSerialize["text"] = o.Text
	}
	return json.Marshal(toSerialize)
}

type NullableRoutesCourseCredits struct {
	value *RoutesCourseCredits
	isSet bool
}

func (v NullableRoutesCourseCredits) Get() *RoutesCourseCredits {
	return v.value
}

func (v *NullableRoutesCourseCredits) Set(val *RoutesCourseCredits) {
	v.value = val
	v.isSet = true
}

func (v NullableRoutesCourseCredits) IsSet() bool {
	return v.isSet
}

func (v *NullableRoutesCourseCredits) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoutesCourseCredits(val *RoutesCourseCredits) *NullableRoutesCourseCredits {
	return &NullableRoutesCourseCredits{value: val, isSet: true}
}

func (v NullableRoutesCourseCredits) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoutesCourseCredits) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


