/*
 * CAMPUSOnline Webservice proxy
 *
 * This is the proxy server for CAMPUSOnline Webservices, enabling a nicely documented and uniform rest access to CAMPUSOnline resources.
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// RoutesContactDataVisitHour struct for RoutesContactDataVisitHour
type RoutesContactDataVisitHour struct {
	Header *string `json:"header,omitempty"`
}

// NewRoutesContactDataVisitHour instantiates a new RoutesContactDataVisitHour object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoutesContactDataVisitHour() *RoutesContactDataVisitHour {
	this := RoutesContactDataVisitHour{}
	return &this
}

// NewRoutesContactDataVisitHourWithDefaults instantiates a new RoutesContactDataVisitHour object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoutesContactDataVisitHourWithDefaults() *RoutesContactDataVisitHour {
	this := RoutesContactDataVisitHour{}
	return &this
}

// GetHeader returns the Header field value if set, zero value otherwise.
func (o *RoutesContactDataVisitHour) GetHeader() string {
	if o == nil || o.Header == nil {
		var ret string
		return ret
	}
	return *o.Header
}

// GetHeaderOk returns a tuple with the Header field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutesContactDataVisitHour) GetHeaderOk() (*string, bool) {
	if o == nil || o.Header == nil {
		return nil, false
	}
	return o.Header, true
}

// HasHeader returns a boolean if a field has been set.
func (o *RoutesContactDataVisitHour) HasHeader() bool {
	if o != nil && o.Header != nil {
		return true
	}

	return false
}

// SetHeader gets a reference to the given string and assigns it to the Header field.
func (o *RoutesContactDataVisitHour) SetHeader(v string) {
	o.Header = &v
}

func (o RoutesContactDataVisitHour) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Header != nil {
		toSerialize["header"] = o.Header
	}
	return json.Marshal(toSerialize)
}

type NullableRoutesContactDataVisitHour struct {
	value *RoutesContactDataVisitHour
	isSet bool
}

func (v NullableRoutesContactDataVisitHour) Get() *RoutesContactDataVisitHour {
	return v.value
}

func (v *NullableRoutesContactDataVisitHour) Set(val *RoutesContactDataVisitHour) {
	v.value = val
	v.isSet = true
}

func (v NullableRoutesContactDataVisitHour) IsSet() bool {
	return v.isSet
}

func (v *NullableRoutesContactDataVisitHour) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoutesContactDataVisitHour(val *RoutesContactDataVisitHour) *NullableRoutesContactDataVisitHour {
	return &NullableRoutesContactDataVisitHour{value: val, isSet: true}
}

func (v NullableRoutesContactDataVisitHour) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoutesContactDataVisitHour) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


