/*
 * CAMPUSOnline Webservice proxy
 *
 * This is the proxy server for CAMPUSOnline Webservices, enabling a nicely documented and uniform rest access to CAMPUSOnline resources.
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// RoutesCourseContacts struct for RoutesCourseContacts
type RoutesCourseContacts struct {
	Person *[]RoutesPerson `json:"person,omitempty"`
}

// NewRoutesCourseContacts instantiates a new RoutesCourseContacts object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoutesCourseContacts() *RoutesCourseContacts {
	this := RoutesCourseContacts{}
	return &this
}

// NewRoutesCourseContactsWithDefaults instantiates a new RoutesCourseContacts object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoutesCourseContactsWithDefaults() *RoutesCourseContacts {
	this := RoutesCourseContacts{}
	return &this
}

// GetPerson returns the Person field value if set, zero value otherwise.
func (o *RoutesCourseContacts) GetPerson() []RoutesPerson {
	if o == nil || o.Person == nil {
		var ret []RoutesPerson
		return ret
	}
	return *o.Person
}

// GetPersonOk returns a tuple with the Person field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutesCourseContacts) GetPersonOk() (*[]RoutesPerson, bool) {
	if o == nil || o.Person == nil {
		return nil, false
	}
	return o.Person, true
}

// HasPerson returns a boolean if a field has been set.
func (o *RoutesCourseContacts) HasPerson() bool {
	if o != nil && o.Person != nil {
		return true
	}

	return false
}

// SetPerson gets a reference to the given []RoutesPerson and assigns it to the Person field.
func (o *RoutesCourseContacts) SetPerson(v []RoutesPerson) {
	o.Person = &v
}

func (o RoutesCourseContacts) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Person != nil {
		toSerialize["person"] = o.Person
	}
	return json.Marshal(toSerialize)
}

type NullableRoutesCourseContacts struct {
	value *RoutesCourseContacts
	isSet bool
}

func (v NullableRoutesCourseContacts) Get() *RoutesCourseContacts {
	return v.value
}

func (v *NullableRoutesCourseContacts) Set(val *RoutesCourseContacts) {
	v.value = val
	v.isSet = true
}

func (v NullableRoutesCourseContacts) IsSet() bool {
	return v.isSet
}

func (v *NullableRoutesCourseContacts) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoutesCourseContacts(val *RoutesCourseContacts) *NullableRoutesCourseContacts {
	return &NullableRoutesCourseContacts{value: val, isSet: true}
}

func (v NullableRoutesCourseContacts) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoutesCourseContacts) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


