/*
 * CAMPUSOnline Webservice proxy
 *
 * This is the proxy server for CAMPUSOnline Webservices, enabling a nicely documented and uniform rest access to CAMPUSOnline resources.
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// RoutesContactDataTelephone struct for RoutesContactDataTelephone
type RoutesContactDataTelephone struct {
	Teltype *string `json:"teltype,omitempty"`
	Text *string `json:"text,omitempty"`
}

// NewRoutesContactDataTelephone instantiates a new RoutesContactDataTelephone object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoutesContactDataTelephone() *RoutesContactDataTelephone {
	this := RoutesContactDataTelephone{}
	return &this
}

// NewRoutesContactDataTelephoneWithDefaults instantiates a new RoutesContactDataTelephone object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoutesContactDataTelephoneWithDefaults() *RoutesContactDataTelephone {
	this := RoutesContactDataTelephone{}
	return &this
}

// GetTeltype returns the Teltype field value if set, zero value otherwise.
func (o *RoutesContactDataTelephone) GetTeltype() string {
	if o == nil || o.Teltype == nil {
		var ret string
		return ret
	}
	return *o.Teltype
}

// GetTeltypeOk returns a tuple with the Teltype field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutesContactDataTelephone) GetTeltypeOk() (*string, bool) {
	if o == nil || o.Teltype == nil {
		return nil, false
	}
	return o.Teltype, true
}

// HasTeltype returns a boolean if a field has been set.
func (o *RoutesContactDataTelephone) HasTeltype() bool {
	if o != nil && o.Teltype != nil {
		return true
	}

	return false
}

// SetTeltype gets a reference to the given string and assigns it to the Teltype field.
func (o *RoutesContactDataTelephone) SetTeltype(v string) {
	o.Teltype = &v
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *RoutesContactDataTelephone) GetText() string {
	if o == nil || o.Text == nil {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutesContactDataTelephone) GetTextOk() (*string, bool) {
	if o == nil || o.Text == nil {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *RoutesContactDataTelephone) HasText() bool {
	if o != nil && o.Text != nil {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *RoutesContactDataTelephone) SetText(v string) {
	o.Text = &v
}

func (o RoutesContactDataTelephone) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Teltype != nil {
		toSerialize["teltype"] = o.Teltype
	}
	if o.Text != nil {
		toSerialize["text"] = o.Text
	}
	return json.Marshal(toSerialize)
}

type NullableRoutesContactDataTelephone struct {
	value *RoutesContactDataTelephone
	isSet bool
}

func (v NullableRoutesContactDataTelephone) Get() *RoutesContactDataTelephone {
	return v.value
}

func (v *NullableRoutesContactDataTelephone) Set(val *RoutesContactDataTelephone) {
	v.value = val
	v.isSet = true
}

func (v NullableRoutesContactDataTelephone) IsSet() bool {
	return v.isSet
}

func (v *NullableRoutesContactDataTelephone) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoutesContactDataTelephone(val *RoutesContactDataTelephone) *NullableRoutesContactDataTelephone {
	return &NullableRoutesContactDataTelephone{value: val, isSet: true}
}

func (v NullableRoutesContactDataTelephone) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoutesContactDataTelephone) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


