/*
 * CAMPUSOnline Webservice proxy
 *
 * This is the proxy server for CAMPUSOnline Webservices, enabling a nicely documented and uniform rest access to CAMPUSOnline resources.
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// RoutesOrgUnitOrgUnitKindSubBlock struct for RoutesOrgUnitOrgUnitKindSubBlock
type RoutesOrgUnitOrgUnitKindSubBlock struct {
	// e.g. \"Lehrstuhl\", \"Arbeitsgruppe\", \"Ausschuss\", ...
	Text *string `json:"text,omitempty"`
	// always \"name\"
	UserDefined *string `json:"userDefined,omitempty"`
}

// NewRoutesOrgUnitOrgUnitKindSubBlock instantiates a new RoutesOrgUnitOrgUnitKindSubBlock object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoutesOrgUnitOrgUnitKindSubBlock() *RoutesOrgUnitOrgUnitKindSubBlock {
	this := RoutesOrgUnitOrgUnitKindSubBlock{}
	return &this
}

// NewRoutesOrgUnitOrgUnitKindSubBlockWithDefaults instantiates a new RoutesOrgUnitOrgUnitKindSubBlock object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoutesOrgUnitOrgUnitKindSubBlockWithDefaults() *RoutesOrgUnitOrgUnitKindSubBlock {
	this := RoutesOrgUnitOrgUnitKindSubBlock{}
	return &this
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *RoutesOrgUnitOrgUnitKindSubBlock) GetText() string {
	if o == nil || o.Text == nil {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutesOrgUnitOrgUnitKindSubBlock) GetTextOk() (*string, bool) {
	if o == nil || o.Text == nil {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *RoutesOrgUnitOrgUnitKindSubBlock) HasText() bool {
	if o != nil && o.Text != nil {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *RoutesOrgUnitOrgUnitKindSubBlock) SetText(v string) {
	o.Text = &v
}

// GetUserDefined returns the UserDefined field value if set, zero value otherwise.
func (o *RoutesOrgUnitOrgUnitKindSubBlock) GetUserDefined() string {
	if o == nil || o.UserDefined == nil {
		var ret string
		return ret
	}
	return *o.UserDefined
}

// GetUserDefinedOk returns a tuple with the UserDefined field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutesOrgUnitOrgUnitKindSubBlock) GetUserDefinedOk() (*string, bool) {
	if o == nil || o.UserDefined == nil {
		return nil, false
	}
	return o.UserDefined, true
}

// HasUserDefined returns a boolean if a field has been set.
func (o *RoutesOrgUnitOrgUnitKindSubBlock) HasUserDefined() bool {
	if o != nil && o.UserDefined != nil {
		return true
	}

	return false
}

// SetUserDefined gets a reference to the given string and assigns it to the UserDefined field.
func (o *RoutesOrgUnitOrgUnitKindSubBlock) SetUserDefined(v string) {
	o.UserDefined = &v
}

func (o RoutesOrgUnitOrgUnitKindSubBlock) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Text != nil {
		toSerialize["text"] = o.Text
	}
	if o.UserDefined != nil {
		toSerialize["userDefined"] = o.UserDefined
	}
	return json.Marshal(toSerialize)
}

type NullableRoutesOrgUnitOrgUnitKindSubBlock struct {
	value *RoutesOrgUnitOrgUnitKindSubBlock
	isSet bool
}

func (v NullableRoutesOrgUnitOrgUnitKindSubBlock) Get() *RoutesOrgUnitOrgUnitKindSubBlock {
	return v.value
}

func (v *NullableRoutesOrgUnitOrgUnitKindSubBlock) Set(val *RoutesOrgUnitOrgUnitKindSubBlock) {
	v.value = val
	v.isSet = true
}

func (v NullableRoutesOrgUnitOrgUnitKindSubBlock) IsSet() bool {
	return v.isSet
}

func (v *NullableRoutesOrgUnitOrgUnitKindSubBlock) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoutesOrgUnitOrgUnitKindSubBlock(val *RoutesOrgUnitOrgUnitKindSubBlock) *NullableRoutesOrgUnitOrgUnitKindSubBlock {
	return &NullableRoutesOrgUnitOrgUnitKindSubBlock{value: val, isSet: true}
}

func (v NullableRoutesOrgUnitOrgUnitKindSubBlock) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoutesOrgUnitOrgUnitKindSubBlock) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


