/*
 * CAMPUSOnline Webservice proxy
 *
 * This is the proxy server for CAMPUSOnline Webservices, enabling a nicely documented and uniform rest access to CAMPUSOnline resources.
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// RoutesCourseAdmissionInfoAdmissionDescription struct for RoutesCourseAdmissionInfoAdmissionDescription
type RoutesCourseAdmissionInfoAdmissionDescription struct {
	UserDefined *string `json:"user_defined,omitempty"`
	WebLink *RoutesWebLink `json:"web_link,omitempty"`
}

// NewRoutesCourseAdmissionInfoAdmissionDescription instantiates a new RoutesCourseAdmissionInfoAdmissionDescription object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoutesCourseAdmissionInfoAdmissionDescription() *RoutesCourseAdmissionInfoAdmissionDescription {
	this := RoutesCourseAdmissionInfoAdmissionDescription{}
	return &this
}

// NewRoutesCourseAdmissionInfoAdmissionDescriptionWithDefaults instantiates a new RoutesCourseAdmissionInfoAdmissionDescription object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoutesCourseAdmissionInfoAdmissionDescriptionWithDefaults() *RoutesCourseAdmissionInfoAdmissionDescription {
	this := RoutesCourseAdmissionInfoAdmissionDescription{}
	return &this
}

// GetUserDefined returns the UserDefined field value if set, zero value otherwise.
func (o *RoutesCourseAdmissionInfoAdmissionDescription) GetUserDefined() string {
	if o == nil || o.UserDefined == nil {
		var ret string
		return ret
	}
	return *o.UserDefined
}

// GetUserDefinedOk returns a tuple with the UserDefined field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutesCourseAdmissionInfoAdmissionDescription) GetUserDefinedOk() (*string, bool) {
	if o == nil || o.UserDefined == nil {
		return nil, false
	}
	return o.UserDefined, true
}

// HasUserDefined returns a boolean if a field has been set.
func (o *RoutesCourseAdmissionInfoAdmissionDescription) HasUserDefined() bool {
	if o != nil && o.UserDefined != nil {
		return true
	}

	return false
}

// SetUserDefined gets a reference to the given string and assigns it to the UserDefined field.
func (o *RoutesCourseAdmissionInfoAdmissionDescription) SetUserDefined(v string) {
	o.UserDefined = &v
}

// GetWebLink returns the WebLink field value if set, zero value otherwise.
func (o *RoutesCourseAdmissionInfoAdmissionDescription) GetWebLink() RoutesWebLink {
	if o == nil || o.WebLink == nil {
		var ret RoutesWebLink
		return ret
	}
	return *o.WebLink
}

// GetWebLinkOk returns a tuple with the WebLink field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutesCourseAdmissionInfoAdmissionDescription) GetWebLinkOk() (*RoutesWebLink, bool) {
	if o == nil || o.WebLink == nil {
		return nil, false
	}
	return o.WebLink, true
}

// HasWebLink returns a boolean if a field has been set.
func (o *RoutesCourseAdmissionInfoAdmissionDescription) HasWebLink() bool {
	if o != nil && o.WebLink != nil {
		return true
	}

	return false
}

// SetWebLink gets a reference to the given RoutesWebLink and assigns it to the WebLink field.
func (o *RoutesCourseAdmissionInfoAdmissionDescription) SetWebLink(v RoutesWebLink) {
	o.WebLink = &v
}

func (o RoutesCourseAdmissionInfoAdmissionDescription) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.UserDefined != nil {
		toSerialize["user_defined"] = o.UserDefined
	}
	if o.WebLink != nil {
		toSerialize["web_link"] = o.WebLink
	}
	return json.Marshal(toSerialize)
}

type NullableRoutesCourseAdmissionInfoAdmissionDescription struct {
	value *RoutesCourseAdmissionInfoAdmissionDescription
	isSet bool
}

func (v NullableRoutesCourseAdmissionInfoAdmissionDescription) Get() *RoutesCourseAdmissionInfoAdmissionDescription {
	return v.value
}

func (v *NullableRoutesCourseAdmissionInfoAdmissionDescription) Set(val *RoutesCourseAdmissionInfoAdmissionDescription) {
	v.value = val
	v.isSet = true
}

func (v NullableRoutesCourseAdmissionInfoAdmissionDescription) IsSet() bool {
	return v.isSet
}

func (v *NullableRoutesCourseAdmissionInfoAdmissionDescription) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoutesCourseAdmissionInfoAdmissionDescription(val *RoutesCourseAdmissionInfoAdmissionDescription) *NullableRoutesCourseAdmissionInfoAdmissionDescription {
	return &NullableRoutesCourseAdmissionInfoAdmissionDescription{value: val, isSet: true}
}

func (v NullableRoutesCourseAdmissionInfoAdmissionDescription) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoutesCourseAdmissionInfoAdmissionDescription) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


