/*
 * CAMPUSOnline Webservice proxy
 *
 * This is the proxy server for CAMPUSOnline Webservices, enabling a nicely documented and uniform rest access to CAMPUSOnline resources.
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// RoutesCourseAdmissionInfo struct for RoutesCourseAdmissionInfo
type RoutesCourseAdmissionInfo struct {
	AdmissionDescription *RoutesCourseAdmissionInfoAdmissionDescription `json:"admission_description,omitempty"`
}

// NewRoutesCourseAdmissionInfo instantiates a new RoutesCourseAdmissionInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoutesCourseAdmissionInfo() *RoutesCourseAdmissionInfo {
	this := RoutesCourseAdmissionInfo{}
	return &this
}

// NewRoutesCourseAdmissionInfoWithDefaults instantiates a new RoutesCourseAdmissionInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoutesCourseAdmissionInfoWithDefaults() *RoutesCourseAdmissionInfo {
	this := RoutesCourseAdmissionInfo{}
	return &this
}

// GetAdmissionDescription returns the AdmissionDescription field value if set, zero value otherwise.
func (o *RoutesCourseAdmissionInfo) GetAdmissionDescription() RoutesCourseAdmissionInfoAdmissionDescription {
	if o == nil || o.AdmissionDescription == nil {
		var ret RoutesCourseAdmissionInfoAdmissionDescription
		return ret
	}
	return *o.AdmissionDescription
}

// GetAdmissionDescriptionOk returns a tuple with the AdmissionDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutesCourseAdmissionInfo) GetAdmissionDescriptionOk() (*RoutesCourseAdmissionInfoAdmissionDescription, bool) {
	if o == nil || o.AdmissionDescription == nil {
		return nil, false
	}
	return o.AdmissionDescription, true
}

// HasAdmissionDescription returns a boolean if a field has been set.
func (o *RoutesCourseAdmissionInfo) HasAdmissionDescription() bool {
	if o != nil && o.AdmissionDescription != nil {
		return true
	}

	return false
}

// SetAdmissionDescription gets a reference to the given RoutesCourseAdmissionInfoAdmissionDescription and assigns it to the AdmissionDescription field.
func (o *RoutesCourseAdmissionInfo) SetAdmissionDescription(v RoutesCourseAdmissionInfoAdmissionDescription) {
	o.AdmissionDescription = &v
}

func (o RoutesCourseAdmissionInfo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AdmissionDescription != nil {
		toSerialize["admission_description"] = o.AdmissionDescription
	}
	return json.Marshal(toSerialize)
}

type NullableRoutesCourseAdmissionInfo struct {
	value *RoutesCourseAdmissionInfo
	isSet bool
}

func (v NullableRoutesCourseAdmissionInfo) Get() *RoutesCourseAdmissionInfo {
	return v.value
}

func (v *NullableRoutesCourseAdmissionInfo) Set(val *RoutesCourseAdmissionInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableRoutesCourseAdmissionInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableRoutesCourseAdmissionInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoutesCourseAdmissionInfo(val *RoutesCourseAdmissionInfo) *NullableRoutesCourseAdmissionInfo {
	return &NullableRoutesCourseAdmissionInfo{value: val, isSet: true}
}

func (v NullableRoutesCourseAdmissionInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoutesCourseAdmissionInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


