/*
 * CAMPUSOnline Webservice proxy
 *
 * This is the proxy server for CAMPUSOnline Webservices, enabling a nicely documented and uniform rest access to CAMPUSOnline resources.
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// RoutesPicture struct for RoutesPicture
type RoutesPicture struct {
	Text *string `json:"text,omitempty"`
	WebLink *RoutesPictureWebLink `json:"web_link,omitempty"`
}

// NewRoutesPicture instantiates a new RoutesPicture object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoutesPicture() *RoutesPicture {
	this := RoutesPicture{}
	return &this
}

// NewRoutesPictureWithDefaults instantiates a new RoutesPicture object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoutesPictureWithDefaults() *RoutesPicture {
	this := RoutesPicture{}
	return &this
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *RoutesPicture) GetText() string {
	if o == nil || o.Text == nil {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutesPicture) GetTextOk() (*string, bool) {
	if o == nil || o.Text == nil {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *RoutesPicture) HasText() bool {
	if o != nil && o.Text != nil {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *RoutesPicture) SetText(v string) {
	o.Text = &v
}

// GetWebLink returns the WebLink field value if set, zero value otherwise.
func (o *RoutesPicture) GetWebLink() RoutesPictureWebLink {
	if o == nil || o.WebLink == nil {
		var ret RoutesPictureWebLink
		return ret
	}
	return *o.WebLink
}

// GetWebLinkOk returns a tuple with the WebLink field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutesPicture) GetWebLinkOk() (*RoutesPictureWebLink, bool) {
	if o == nil || o.WebLink == nil {
		return nil, false
	}
	return o.WebLink, true
}

// HasWebLink returns a boolean if a field has been set.
func (o *RoutesPicture) HasWebLink() bool {
	if o != nil && o.WebLink != nil {
		return true
	}

	return false
}

// SetWebLink gets a reference to the given RoutesPictureWebLink and assigns it to the WebLink field.
func (o *RoutesPicture) SetWebLink(v RoutesPictureWebLink) {
	o.WebLink = &v
}

func (o RoutesPicture) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Text != nil {
		toSerialize["text"] = o.Text
	}
	if o.WebLink != nil {
		toSerialize["web_link"] = o.WebLink
	}
	return json.Marshal(toSerialize)
}

type NullableRoutesPicture struct {
	value *RoutesPicture
	isSet bool
}

func (v NullableRoutesPicture) Get() *RoutesPicture {
	return v.value
}

func (v *NullableRoutesPicture) Set(val *RoutesPicture) {
	v.value = val
	v.isSet = true
}

func (v NullableRoutesPicture) IsSet() bool {
	return v.isSet
}

func (v *NullableRoutesPicture) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoutesPicture(val *RoutesPicture) *NullableRoutesPicture {
	return &NullableRoutesPicture{value: val, isSet: true}
}

func (v NullableRoutesPicture) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoutesPicture) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


