/*
 * CAMPUSOnline Webservice proxy
 *
 * This is the proxy server for CAMPUSOnline Webservices, enabling a nicely documented and uniform rest access to CAMPUSOnline resources.
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// RoutesCourseCourseName struct for RoutesCourseCourseName
type RoutesCourseCourseName struct {
	Text *string `json:"text,omitempty"`
}

// NewRoutesCourseCourseName instantiates a new RoutesCourseCourseName object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoutesCourseCourseName() *RoutesCourseCourseName {
	this := RoutesCourseCourseName{}
	return &this
}

// NewRoutesCourseCourseNameWithDefaults instantiates a new RoutesCourseCourseName object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoutesCourseCourseNameWithDefaults() *RoutesCourseCourseName {
	this := RoutesCourseCourseName{}
	return &this
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *RoutesCourseCourseName) GetText() string {
	if o == nil || o.Text == nil {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutesCourseCourseName) GetTextOk() (*string, bool) {
	if o == nil || o.Text == nil {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *RoutesCourseCourseName) HasText() bool {
	if o != nil && o.Text != nil {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *RoutesCourseCourseName) SetText(v string) {
	o.Text = &v
}

func (o RoutesCourseCourseName) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Text != nil {
		toSerialize["text"] = o.Text
	}
	return json.Marshal(toSerialize)
}

type NullableRoutesCourseCourseName struct {
	value *RoutesCourseCourseName
	isSet bool
}

func (v NullableRoutesCourseCourseName) Get() *RoutesCourseCourseName {
	return v.value
}

func (v *NullableRoutesCourseCourseName) Set(val *RoutesCourseCourseName) {
	v.value = val
	v.isSet = true
}

func (v NullableRoutesCourseCourseName) IsSet() bool {
	return v.isSet
}

func (v *NullableRoutesCourseCourseName) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoutesCourseCourseName(val *RoutesCourseCourseName) *NullableRoutesCourseCourseName {
	return &NullableRoutesCourseCourseName{value: val, isSet: true}
}

func (v NullableRoutesCourseCourseName) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoutesCourseCourseName) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


