/*
 * CAMPUSOnline Webservice proxy
 *
 * This is the proxy server for CAMPUSOnline Webservices, enabling a nicely documented and uniform rest access to CAMPUSOnline resources.
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// RoutesOrgUnit struct for RoutesOrgUnit
type RoutesOrgUnit struct {
	Contacts *RoutesOrgUnitContacts `json:"contacts,omitempty"`
	InfoBlock *RoutesInfoBlock `json:"infoBlock,omitempty"`
	OrgUnitCode *string `json:"orgUnitCode,omitempty"`
	OrgUnitID *string `json:"orgUnitID,omitempty"`
	OrgUnitKind *RoutesOrgUnitOrgUnitKind `json:"orgUnitKind,omitempty"`
	OrgUnitName *RoutesContactDataContactName `json:"orgUnitName,omitempty"`
	OrgUnits *[]RoutesOrgUnit `json:"orgUnits,omitempty"`
	Text *string `json:"text,omitempty"`
}

// NewRoutesOrgUnit instantiates a new RoutesOrgUnit object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoutesOrgUnit() *RoutesOrgUnit {
	this := RoutesOrgUnit{}
	return &this
}

// NewRoutesOrgUnitWithDefaults instantiates a new RoutesOrgUnit object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoutesOrgUnitWithDefaults() *RoutesOrgUnit {
	this := RoutesOrgUnit{}
	return &this
}

// GetContacts returns the Contacts field value if set, zero value otherwise.
func (o *RoutesOrgUnit) GetContacts() RoutesOrgUnitContacts {
	if o == nil || o.Contacts == nil {
		var ret RoutesOrgUnitContacts
		return ret
	}
	return *o.Contacts
}

// GetContactsOk returns a tuple with the Contacts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutesOrgUnit) GetContactsOk() (*RoutesOrgUnitContacts, bool) {
	if o == nil || o.Contacts == nil {
		return nil, false
	}
	return o.Contacts, true
}

// HasContacts returns a boolean if a field has been set.
func (o *RoutesOrgUnit) HasContacts() bool {
	if o != nil && o.Contacts != nil {
		return true
	}

	return false
}

// SetContacts gets a reference to the given RoutesOrgUnitContacts and assigns it to the Contacts field.
func (o *RoutesOrgUnit) SetContacts(v RoutesOrgUnitContacts) {
	o.Contacts = &v
}

// GetInfoBlock returns the InfoBlock field value if set, zero value otherwise.
func (o *RoutesOrgUnit) GetInfoBlock() RoutesInfoBlock {
	if o == nil || o.InfoBlock == nil {
		var ret RoutesInfoBlock
		return ret
	}
	return *o.InfoBlock
}

// GetInfoBlockOk returns a tuple with the InfoBlock field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutesOrgUnit) GetInfoBlockOk() (*RoutesInfoBlock, bool) {
	if o == nil || o.InfoBlock == nil {
		return nil, false
	}
	return o.InfoBlock, true
}

// HasInfoBlock returns a boolean if a field has been set.
func (o *RoutesOrgUnit) HasInfoBlock() bool {
	if o != nil && o.InfoBlock != nil {
		return true
	}

	return false
}

// SetInfoBlock gets a reference to the given RoutesInfoBlock and assigns it to the InfoBlock field.
func (o *RoutesOrgUnit) SetInfoBlock(v RoutesInfoBlock) {
	o.InfoBlock = &v
}

// GetOrgUnitCode returns the OrgUnitCode field value if set, zero value otherwise.
func (o *RoutesOrgUnit) GetOrgUnitCode() string {
	if o == nil || o.OrgUnitCode == nil {
		var ret string
		return ret
	}
	return *o.OrgUnitCode
}

// GetOrgUnitCodeOk returns a tuple with the OrgUnitCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutesOrgUnit) GetOrgUnitCodeOk() (*string, bool) {
	if o == nil || o.OrgUnitCode == nil {
		return nil, false
	}
	return o.OrgUnitCode, true
}

// HasOrgUnitCode returns a boolean if a field has been set.
func (o *RoutesOrgUnit) HasOrgUnitCode() bool {
	if o != nil && o.OrgUnitCode != nil {
		return true
	}

	return false
}

// SetOrgUnitCode gets a reference to the given string and assigns it to the OrgUnitCode field.
func (o *RoutesOrgUnit) SetOrgUnitCode(v string) {
	o.OrgUnitCode = &v
}

// GetOrgUnitID returns the OrgUnitID field value if set, zero value otherwise.
func (o *RoutesOrgUnit) GetOrgUnitID() string {
	if o == nil || o.OrgUnitID == nil {
		var ret string
		return ret
	}
	return *o.OrgUnitID
}

// GetOrgUnitIDOk returns a tuple with the OrgUnitID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutesOrgUnit) GetOrgUnitIDOk() (*string, bool) {
	if o == nil || o.OrgUnitID == nil {
		return nil, false
	}
	return o.OrgUnitID, true
}

// HasOrgUnitID returns a boolean if a field has been set.
func (o *RoutesOrgUnit) HasOrgUnitID() bool {
	if o != nil && o.OrgUnitID != nil {
		return true
	}

	return false
}

// SetOrgUnitID gets a reference to the given string and assigns it to the OrgUnitID field.
func (o *RoutesOrgUnit) SetOrgUnitID(v string) {
	o.OrgUnitID = &v
}

// GetOrgUnitKind returns the OrgUnitKind field value if set, zero value otherwise.
func (o *RoutesOrgUnit) GetOrgUnitKind() RoutesOrgUnitOrgUnitKind {
	if o == nil || o.OrgUnitKind == nil {
		var ret RoutesOrgUnitOrgUnitKind
		return ret
	}
	return *o.OrgUnitKind
}

// GetOrgUnitKindOk returns a tuple with the OrgUnitKind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutesOrgUnit) GetOrgUnitKindOk() (*RoutesOrgUnitOrgUnitKind, bool) {
	if o == nil || o.OrgUnitKind == nil {
		return nil, false
	}
	return o.OrgUnitKind, true
}

// HasOrgUnitKind returns a boolean if a field has been set.
func (o *RoutesOrgUnit) HasOrgUnitKind() bool {
	if o != nil && o.OrgUnitKind != nil {
		return true
	}

	return false
}

// SetOrgUnitKind gets a reference to the given RoutesOrgUnitOrgUnitKind and assigns it to the OrgUnitKind field.
func (o *RoutesOrgUnit) SetOrgUnitKind(v RoutesOrgUnitOrgUnitKind) {
	o.OrgUnitKind = &v
}

// GetOrgUnitName returns the OrgUnitName field value if set, zero value otherwise.
func (o *RoutesOrgUnit) GetOrgUnitName() RoutesContactDataContactName {
	if o == nil || o.OrgUnitName == nil {
		var ret RoutesContactDataContactName
		return ret
	}
	return *o.OrgUnitName
}

// GetOrgUnitNameOk returns a tuple with the OrgUnitName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutesOrgUnit) GetOrgUnitNameOk() (*RoutesContactDataContactName, bool) {
	if o == nil || o.OrgUnitName == nil {
		return nil, false
	}
	return o.OrgUnitName, true
}

// HasOrgUnitName returns a boolean if a field has been set.
func (o *RoutesOrgUnit) HasOrgUnitName() bool {
	if o != nil && o.OrgUnitName != nil {
		return true
	}

	return false
}

// SetOrgUnitName gets a reference to the given RoutesContactDataContactName and assigns it to the OrgUnitName field.
func (o *RoutesOrgUnit) SetOrgUnitName(v RoutesContactDataContactName) {
	o.OrgUnitName = &v
}

// GetOrgUnits returns the OrgUnits field value if set, zero value otherwise.
func (o *RoutesOrgUnit) GetOrgUnits() []RoutesOrgUnit {
	if o == nil || o.OrgUnits == nil {
		var ret []RoutesOrgUnit
		return ret
	}
	return *o.OrgUnits
}

// GetOrgUnitsOk returns a tuple with the OrgUnits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutesOrgUnit) GetOrgUnitsOk() (*[]RoutesOrgUnit, bool) {
	if o == nil || o.OrgUnits == nil {
		return nil, false
	}
	return o.OrgUnits, true
}

// HasOrgUnits returns a boolean if a field has been set.
func (o *RoutesOrgUnit) HasOrgUnits() bool {
	if o != nil && o.OrgUnits != nil {
		return true
	}

	return false
}

// SetOrgUnits gets a reference to the given []RoutesOrgUnit and assigns it to the OrgUnits field.
func (o *RoutesOrgUnit) SetOrgUnits(v []RoutesOrgUnit) {
	o.OrgUnits = &v
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *RoutesOrgUnit) GetText() string {
	if o == nil || o.Text == nil {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutesOrgUnit) GetTextOk() (*string, bool) {
	if o == nil || o.Text == nil {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *RoutesOrgUnit) HasText() bool {
	if o != nil && o.Text != nil {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *RoutesOrgUnit) SetText(v string) {
	o.Text = &v
}

func (o RoutesOrgUnit) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Contacts != nil {
		toSerialize["contacts"] = o.Contacts
	}
	if o.InfoBlock != nil {
		toSerialize["infoBlock"] = o.InfoBlock
	}
	if o.OrgUnitCode != nil {
		toSerialize["orgUnitCode"] = o.OrgUnitCode
	}
	if o.OrgUnitID != nil {
		toSerialize["orgUnitID"] = o.OrgUnitID
	}
	if o.OrgUnitKind != nil {
		toSerialize["orgUnitKind"] = o.OrgUnitKind
	}
	if o.OrgUnitName != nil {
		toSerialize["orgUnitName"] = o.OrgUnitName
	}
	if o.OrgUnits != nil {
		toSerialize["orgUnits"] = o.OrgUnits
	}
	if o.Text != nil {
		toSerialize["text"] = o.Text
	}
	return json.Marshal(toSerialize)
}

type NullableRoutesOrgUnit struct {
	value *RoutesOrgUnit
	isSet bool
}

func (v NullableRoutesOrgUnit) Get() *RoutesOrgUnit {
	return v.value
}

func (v *NullableRoutesOrgUnit) Set(val *RoutesOrgUnit) {
	v.value = val
	v.isSet = true
}

func (v NullableRoutesOrgUnit) IsSet() bool {
	return v.isSet
}

func (v *NullableRoutesOrgUnit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoutesOrgUnit(val *RoutesOrgUnit) *NullableRoutesOrgUnit {
	return &NullableRoutesOrgUnit{value: val, isSet: true}
}

func (v NullableRoutesOrgUnit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoutesOrgUnit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


