/*
 * CAMPUSOnline Webservice proxy
 *
 * This is the proxy server for CAMPUSOnline Webservices, enabling a nicely documented and uniform rest access to CAMPUSOnline resources.
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// RoutesApiError struct for RoutesApiError
type RoutesApiError struct {
	Msg *string `json:"msg,omitempty"`
	Status *int32 `json:"status,omitempty"`
}

// NewRoutesApiError instantiates a new RoutesApiError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoutesApiError() *RoutesApiError {
	this := RoutesApiError{}
	return &this
}

// NewRoutesApiErrorWithDefaults instantiates a new RoutesApiError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoutesApiErrorWithDefaults() *RoutesApiError {
	this := RoutesApiError{}
	return &this
}

// GetMsg returns the Msg field value if set, zero value otherwise.
func (o *RoutesApiError) GetMsg() string {
	if o == nil || o.Msg == nil {
		var ret string
		return ret
	}
	return *o.Msg
}

// GetMsgOk returns a tuple with the Msg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutesApiError) GetMsgOk() (*string, bool) {
	if o == nil || o.Msg == nil {
		return nil, false
	}
	return o.Msg, true
}

// HasMsg returns a boolean if a field has been set.
func (o *RoutesApiError) HasMsg() bool {
	if o != nil && o.Msg != nil {
		return true
	}

	return false
}

// SetMsg gets a reference to the given string and assigns it to the Msg field.
func (o *RoutesApiError) SetMsg(v string) {
	o.Msg = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *RoutesApiError) GetStatus() int32 {
	if o == nil || o.Status == nil {
		var ret int32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutesApiError) GetStatusOk() (*int32, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *RoutesApiError) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given int32 and assigns it to the Status field.
func (o *RoutesApiError) SetStatus(v int32) {
	o.Status = &v
}

func (o RoutesApiError) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Msg != nil {
		toSerialize["msg"] = o.Msg
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	return json.Marshal(toSerialize)
}

type NullableRoutesApiError struct {
	value *RoutesApiError
	isSet bool
}

func (v NullableRoutesApiError) Get() *RoutesApiError {
	return v.value
}

func (v *NullableRoutesApiError) Set(val *RoutesApiError) {
	v.value = val
	v.isSet = true
}

func (v NullableRoutesApiError) IsSet() bool {
	return v.isSet
}

func (v *NullableRoutesApiError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoutesApiError(val *RoutesApiError) *NullableRoutesApiError {
	return &NullableRoutesApiError{value: val, isSet: true}
}

func (v NullableRoutesApiError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoutesApiError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


